### ISSUE TITLE
Hi 推荐一个免除在字符串中编写 snippet 代码的麻烦的解决方案

### ISSUE THREAD

**Issue by codetalks-new** [onvno/code-rhythm#1]
https://github.com/banxi1988/vscode-snippets-ext-template

简而言之就是将 snippet 代码写在单独的代码文件中。
然后使用 nodejs 脚本处理合并成最终的 snippets.json 文件。
这样就不用在 snippets.json 中的字符串的写代码。

**Comment by onvno** [comment]
多谢，其实目前也在用一个方案。issue先不关，会了解下。

**Comment by onvno** [comment]
@banxi1988 目前在处理这部分逻辑，使用了yaml进行代码片段整理，多谢。

**Comment by codetalks-new** [comment]
@onvno 还是推荐一下我的方案，比如补全代码是  js 代码
可以使用 js 文件来写，这样代码有语法高亮，自动格式化等。总之可以利用vscode对对应语法文件的支持。 
使用 yaml 的话，虽然可以做到多行文本，但是也仅仅是多行文本。
