### ISSUE TITLE
能否支持自定义呢，想设置新特性，修改自己的方式呢：）

### ISSUE THREAD

**Issue by wentoos** [onvno/code-rhythm#3]

**Comment by onvno** [comment]
@wentoos 抱歉回复的晚了，最近在搞一个好玩的小项目中。issue先不关，我想想有什么好的办法可以满足自定义的需求。
另外之前的代码示例有些过于简单，有些又有点啰嗦，想先把这部分优化了。多谢。

**Comment by onvno** [comment]
@wentoos 前段时间一直在更新维护自己写的一个 chrome扩展。目前已经在dev分支在处理这部分逻辑，既可以利用`npm run build`创建自己的代码片段，也可以提pr用来合并你的代码。本周会更新仓库&扩展&如何自定义新特性的文档

**Comment by onvno** [comment]
@wentoos 针对自定义代码片段，抽了一个工具应该能满足你的需求：[snippet-builder](https://github.com/onvno/snippet-builder)

**Comment by wentoos** [comment]
厉害了，厉害了，
